from crewai.flow import Flow, listen, start
from pydantic import BaseModel
from typing import Optional 
from flow_defining.crews.research_crew.research_crew import ResearchCrew
from flow_defining.crews.writing_crew.writing_crew import WritingCrew



class ResearchFlowState(BaseModel):
    youtube_links: Optional[str] = ""
    webpage_links:  Optional[str] = ""
    research_paper_links: Optional[str] = ""
    document_paths: Optional[str] = ""

    research_report : str|None = None
    final_guide : str|None = None



class GuideGeneratorFlow(Flow[ResearchFlowState]):
    """
    Main flow that orchestrates the complete guide generation process.
    
    Flow Steps:
    1. receive_user_inputs - Accept and Validate user inputs
    2. run_research_crew - Execute Crew 1 (hierarchical research)
    3. run_writing_crew - Execute Crew 2 (sequential writing)
    """

    @start()
    def receive_user_input(self) ->str:
        sources_provided = []
        
        if self.state.youtube_links:
            sources_provided.append("YouTube")
        if self.state.webpage_links:
            sources_provided.append("Web Pages")
        if self.state.document_paths:
            sources_provided.append("Documents")
        if self.state.research_paper_links:
            sources_provided.append("Research Papers")
            
        if not sources_provided:
            return "no_sources"
        
        return "inputs_received"
    

    @listen(receive_user_input)
    def run_research_crew(self, prev_output) -> str:
        """
        Executes Crew 1: Research Crew
        
        The research crew uses a manager agent to coordinate 4 specialists
        who gather information from different source types. The manager then
        compiles everything into a comprehensive research report
        """
        
        if prev_output == "no_sources":
            return "research_skipped"
        
        elif prev_output == "inputs_received":
            
            try:
                # initialize my research crew
                research_crew = ResearchCrew().crew()
                
                # execute the crew with provided sources
                result = research_crew.kickoff(inputs={
                    "youtube_links": self.state.youtube_links or "Not provided",
                    "webpage_links": self.state.webpage_links or "Not provided",
                    "research_paper_links": self.state.research_paper_links or "Not provided",
                    "document_paths": self.state.document_paths or "Not provided"
                })
                
                # store the research report into state
                self.state.research_report = result.raw
                
                return "research_complete"

            except Exception as e:
                return "research_failed"
            
    @listen(run_research_crew)
    def run_writing_crew(self, prev_output) -> str:
        """
        Executes Crew 2: Writing Crew
        
        The writing crew takes the research report generated by the research crew
        and produces a final guide. It uses a manager agent to coordinate 3 specialists
        who handle different aspects of the writing process.
        """
        
        if prev_output == "research_skipped":
            return "writing_skipped"
        
        if prev_output == "research_failed":
            return "writing_skipped"
        
        elif prev_output == "research_complete":
            
            try:

                # initialize my writing crew
                writing_crew = WritingCrew().crew()

                result = writing_crew.kickoff(inputs={
                    "research_report": self.state.research_report
                })
                self.state.final_guide = result.raw
                return "writing_complete"

                
                # execute
            except Exception as e:
                return "writing_failed"


def get_inputs():
    youtube_links = input("Enter YouTube links (comma-separated or press enter to skip): ")
    webpage_links = input("Enter webpage links (comma-separated or press enter to skip): ")
    research_paper_links = input("Enter research paper links (comma-separated or press enter to skip): ")
    document_paths = input("Enter document paths (comma-separated or press enter to skip): ")

    return {
        "youtube_links": youtube_links,
        "webpage_links": webpage_links,
        "research_paper_links": research_paper_links,
        "document_paths": document_paths
    }


def kickoff():
    inputs = get_inputs()

    flow = GuideGeneratorFlow()

    flow_result = flow.kickoff(inputs)
    print("\nFinal Flow Result:")
    print(flow_result)


if __name__ == "__main__":
    kickoff()